import './globals.css'
import type { Metadata } from 'next'
import { breeSerif, lato, openSans } from './fonts'
import { ProviderInfoUser } from '@/context/ContextUser'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang='en'>
      <body className={`${lato.variable} font-lato text-white ${breeSerif.variable} font-bree_serif text-white ${openSans.variable} font-open_sans text-white`}><ProviderInfoUser>{children}</ProviderInfoUser></body>
    </html>
  )
}
